Release/camelize
ridi/object-case-converter pull request #5
Opened 2018-03-06 10:38 UTC by J132134

tslint 적용 및 README.md 간단하게 수정했습니다.
추가 되어야할 내용 코멘트 부탁드립니다.

2018-03-07 01:21 UTC, kyungmi requested changes

2018-03-07 01:21 UTC, kyungmi commented on .npmignore
> +.travis.yml
node_modules는 왜 빠진건가요?

2018-03-07 01:21 UTC, kyungmi commented on README.md
> +Convert keys in an object or objects in an array to `camelize`
`camelCase`라고 명확하게 써주는게 좋을 것 같아요.

2018-03-07 01:21 UTC, kyungmi commented on README.md
> +    * recursive - convert only matched key as recursive
`recursive`와 `excludes`의 기본 값도 써주세요.
`recursive`는 `false`가 기본값이라 적지 않으신 것 같은데 타입을 쓰신거니까 `boolean`이라고 적는게 좋을 것 같아요.
`recursive`의 depth 개념은 없어진건가요?

2018-03-07 01:21 UTC, kyungmi commented on README.md
> +    * excludes - escape when key includes in string[] or when function or RegExp.test() are return true
"set keys that are prevented from converting(presented by array of keys, `RegExp`, or `function`) " 라고 적는게 좋을 것 같아요.

2018-03-07 01:21 UTC, kyungmi commented on README.md
> +Convert keys in an object or objects in an array **that are camelCase** to `snake_case`
`style` 개념도 없어진건가요?
"only"를 써서 "only for keys in `camelCase`" 라고 표현해주면 더 명확할 것 같아요.

2018-03-07 01:21 UTC, kyungmi commented on README.md
> +    * exception - when key has been owned by exception object, convert to value specified string or function return
exception - "set keys that need exceptional converting method" 는 어떨까요?

2018-03-07 01:21 UTC, kyungmi commented on README.md
> +Convert keys in an object or objects in an array **that are camelCase** to `snake_case`
`style`이 옵션에서 사라지고 나니, `camelize`는 모든 케이스들을 camelCase로 변환하는데 `decamelize`는 camelCase일때만 변환하게 되어 있어서 아무런 옵션 없이 사용했을 때 `camelize`와 `decamelize`가 완전히 역이 아닌게 마음에 걸리네요. 

```
obj == decamelize(camelize(obj)) // 가 성립하지 않을 것 같아요.
```

2018-03-07 01:21 UTC, kyungmi commented on src/__tests__/camelize.ts
> +  })
`{ excludes: ['FOO'], recursive: true }`와 `{ excludes: ['FOO'], recursive: { excludes: ['FOO'] } }`가 같은건가요? 
위에건 
```
{
  FOO: {
    fooBar: '',
  },
  ...
}
```
가 되고 아래건
```
{
  FOO: {
    foo_bar: '',
  },
  ...
}
```
가 될 것 같아서요.

2018-03-07 01:21 UTC, kyungmi commented on src/__tests__/camelize.ts
> +      .toEqual(camelize(result, { excludes: ['FOO'], recursive: { excludes: ['foo_baz', 'FOO'] } }))
이런 비교는 위험할 것 같습니다. 자칫 두 결과가 `result`에 상관 없이 항상 같은 것으로 오인될 수 있어서요.

2018-03-07 01:21 UTC, kyungmi commented on src/camelize.ts
> +export interface Exception { [key: string]: string | ((key?: string) => string); }
TS에서의 사용 방법은 `Exception`을 implementation해서 쓰게 되는건가요?
이걸 보니까 ES6에서의 사용법 말고도 TypeScript로 이 라이브러리를 쓸 때의 사용법도 같이 있으면 좋을 것 같네요.

2018-03-07 01:21 UTC, kyungmi commented on README.md
>  ## Development
더 이상 Webpack을 쓰지 않기 때문에 이 섹션도 업데이트가 필요하겠네요.
빌드 방식 업데이트 부탁드려요.

2018-03-07 01:23 UTC, kyungmi commented on src/__tests__/camelize.ts
> +  })
근데 테스트는 해보니 통과하는 것 같네요. 음.. 제가 잘못 이해한건가요? 이제 옵션은 정확히 알게 되었다고 생각했는데

2018-03-07 02:27 UTC, J132134 commented on README.md
> +    * recursive - convert only matched key as recursive
넵. recursive를 적용할 key array로 대체했습니다.

2018-03-07 02:36 UTC, J132134 commented on src/__tests__/camelize.ts
> +  })
{ excludes: ['FOO'] } 와 같이 camelCase로 변환하지 않는 경우는 `foo.FOO.bar` 또는 `const { FOO } = foo`; 같이 js에서 접근하지 않을 것 같아 recursive로 변환할 필요가 없다고 판단했습니다.
논리적으로는 recursive 옵션이 camelize excludes를 상속받는다고 보시면 될 것 같습니다.
이견이 없으시면 문서에 추가하도록 하겠습니다.

2018-03-07 02:44 UTC, J132134 commented on .npmignore
> +.travis.yml
넣어주지 않아도 node_modules 는 제외됩니다

https://docs.npmjs.com/misc/developers
Additionally, everything in node_modules is ignored, except for bundled dependencies. npm automatically handles this for you, **so don't bother adding node_modules to .npmignore.**

2018-03-07 02:48 UTC, J132134 commented on README.md
> +Convert keys in an object or objects in an array **that are camelCase** to `snake_case`
`obj == decamelize(camelize(obj))` 는 force 옵션 여부와 상관없이 성립하지 않습니다..

2018-03-07 02:48 UTC, J132134 commented on src/__tests__/camelize.ts
> +      .toEqual(camelize(result, { excludes: ['FOO'], recursive: { excludes: ['foo_baz', 'FOO'] } }))
수정하겠습니다!

2018-03-07 02:51 UTC, kyungmi requested changes

2018-03-07 02:51 UTC, kyungmi commented on src/__tests__/camelize.ts
> +  })
@J132134 `isRecursive()` 함수에서 다음의 두 경우에 `!isExclude(key)` 여부를 함께 체크하고 있는 것 같네요.

1. `recursive.excludes`가 array일 경우
2. `recursive`가 true인 경우

```
    if (typeof recursive === 'object' && Array.isArray(recursive.excludes)) {
      return (key) => !isExclude(key) && !recursive.excludes.includes(key);
    }
    if (recursive === true) {
      return (key) => !isExclude(key);
    }
```
전에 한번 질문 드렸던거 같은데, `excludes`가 `mapObject()` 과정에도 영향을 주는 식으로 동작한다면, 어차피 `recursive.excludes`는 string[] 타입밖에 받을수가 없으므로, `recursive.excludes`를 없애고 `excludes` 옵션만 남기는게 맞지 않을까요?

2018-03-07 02:53 UTC, kyungmi commented on README.md
> +Convert keys in an object or objects in an array **that are camelCase** to `snake_case`
의도도 전달이 안됐나요? ㅎㅎ

2018-03-07 02:56 UTC, J132134 commented on src/camelize.ts
> +export interface Exception { [key: string]: string | ((key?: string) => string); }
TS에서도 라이브러리 사용법은 동일합니다. type과 interface도 표현과 세부 기능의 차이가 있고 기본적인 기능은 동일합니다

2018-03-07 02:56 UTC, J132134 commented on README.md
>  ## Development
넵

2018-03-07 03:04 UTC, kyungmi commented on src/camelize.ts
> +export interface Exception { [key: string]: string | ((key?: string) => string); }
아하 그렇군요

2018-03-07 03:04 UTC, kyungmi commented
`@ridi/tslint-config`는 언제 배포 예정인가요?

2018-03-07 03:36 UTC, J132134 commented on src/__tests__/camelize.ts
> +  })
recursive.excludes는 recursive에만 영향을 주고 excludes는 키 변환과 recursive에 모두 영향을 줍니다.
말씀하신대로 하면 키만 변환하고 value인 object는 recursive로 변환하고 싶지 않은 경우 사용할 방법이 없습니다.
두번째는 camelCase이거나 모두 소문자로만 이루어진 키인 경우에도 내부 변환을 막기 위해서 excludes에 포함해야 하기 때문에 excludes의 용도가 불분명해지는 것 같습니다.

```
const obj = { FOO: { BAR: '', BAZ: '' } }
const { foo } = camelize(obj, {recursive: { excludes: ['FOO'] })
ajax.post('', { data: foo }) // { BAR: '', BAZ: '' }
```
와 같이 사용하거나 `camelize(obj, { excludes: /^[A-Z0-9_]+$/, recursive: { exlucdes: ['foo'] }` 처럼 사용할 수 있습니다.

2018-03-07 03:36 UTC, J132134 commented on README.md
> +Convert keys in an object or objects in an array **that are camelCase** to `snake_case`
현재 코드도 (메소드 이름에서 기대되는 동작으로) 의견이 반영된 결과입니다.

스토어 팀 내 설계 의도는
camelize: whatever  -> **camelCase**
decamelize: **camelCase** -> snake_case (or others)
로, camelCase <-> snake_case 상호변환이 아니었습니다.

2018-03-07 03:41 UTC, kyungmi commented on README.md
> +Convert keys in an object or objects in an array **that are camelCase** to `snake_case`
메소드 이름에서 기대되는 동작이라고 하시면 할 말이 없네요. ㅎㅎ
지금 와서 구현 내용을 바꾸는 것도 비용이니 요 논의는 없던 것으로 하겠습니다.

2018-03-07 03:46 UTC, kyungmi commented on src/__tests__/camelize.ts
> +  })
`키만 변환하고 value인 object는 recursive로 변환하고 싶지 않은 경우`의 케이스가 존재하지 않아서 이렇게 설계하신 줄 알았네요.

`recursive`옵션의 설정 값(string[]이냐 다른 값이냐)에 따라 `excludes` 옵션이 recursive한 동작에 영향을 줄 수도, 안 줄수도 있게 되어 있는데, 이렇게 하는게 더 불분명한 것 같습니다. 이것보다는 `recursive.excludes`도 string[], RegExp, function 세 종류로 받을 수 있게 하면 되지 않을까요?

2018-03-07 09:13 UTC, kyungmi commented on README.md
> +    * excludes - excludes from convertion
`convertion` -> `conversion`

2018-03-07 09:18 UTC, kyungmi requested changes

2018-03-07 09:18 UTC, kyungmi commented on README.md
> +  * string[] -- excludes from convertion if key is in the array
`convertion` => `conversion`

2018-03-09 07:26 UTC, J132134 commented on src/__tests__/camelize.ts
> +  })
recursive의 타입을 false와 string[]는 `negative`로, true와 { excludes }는 `positive`로 구분할 수 있는데 negative인 경우에는 excludes 옵션에 영향을 받지않기 때문에 그렇게 보일 뿐입니다.

먼저 결정되어야 하는게, camelize 함수의 의도가 서버에서 받은 snake_case 포맷을 lint를 준수하는 js에서 변수로 접근할때 사용하는 것이기 때문에 camelCase로 변환하지 않는 키는 js에서 사용하지 않는다는 전제입니다.

위 전제가 맞다면 지금 형태가 합리적인 구조라고 판단되고, 전제가 옳지 않다면 string[]의 나열을 줄이기 위해서 제안해주신 방법대로 recursive.excludes가 excludes와 같은 형태를 받아야 할 것 같습니다. 그렇게하면 스토어팀의 대부분의 코드에서는 excludes의 값과 recursive.excludes의 값이 중복되는 경우가 많을 것 같습니다.

2018-03-09 07:28 UTC, J132134 commented on src/__tests__/camelize.ts
> +      .toEqual(camelize(result, { excludes: ['FOO'], recursive: { excludes: ['foo_baz', 'FOO'] } }))
result가 다르더라도 두 결과값은 같은 것이 맞는 것 같습니다.
테스트 케이스의 타이틀처럼 개념적으로는 recursive.excludes가 excludes를 상속합니다.

2018-03-09 07:31 UTC, J132134 commented
`@ridi/tslint-config`의 배포 일정이 정해지지 않았고, OCC에 의존성을 가진 `@ridi/rsg`의 배포 일정이 임박하여 규칙을 복사해두고 패키지 의존성은 제거해두었습니다. 추후 다시 적용하도록 하겠습니다.

2018-03-09 07:40 UTC, kyungmi commented on src/__tests__/camelize.ts
> +  })
일단 공통 라이브러리므로, 'camelize 함수의 의도가 서버에서 받은 snake_case 포맷을 lint를 준수하는 js에서 변수로 접근할때 사용하는 것이기 때문에 camelCase로 변환하지 않는 키는 js에서 사용하지 않는다'와 같은 프로젝트 specific한 전제를 깔지 않는게 좋다고 생각합니다.

그리고 API를 보았을때 `string[]`이 `negative`라고 느껴지지 않고, `positive`라고 느껴집니다.
저는 `recursive: false` 외에는 모두 recursive 옵션을 켜는 것으로 느껴지고 다른 설정들은 `reculsive: true`의 상세 설정(`string[]`의 경우는 `includes`, `{excludes: ...}` 의 경우에는 `excludes`)으로 보입니다.
그리고 그렇게 이해를 하고 있었기 때문에, '스토어팀의 대부분의 코드에서는 `excludes`의 값과 `recursive.excludes`의 값이 중복되는 경우'에 대해서 얘기하시면서 편의성을 언급하신 것 같은데, 제 관점에서는 편의성을 얻고 일관성을 잃는다는 생각이 들고요.

제 경우에 그렇다는 뜻이고요. 다른 분들 의견도 궁금하네요. @namenu @earus @nnyamm @gyujincho

2018-03-09 08:33 UTC, J132134 commented on src/__tests__/camelize.ts
> +  })
negative/positive의 용어나 개념이 중요한건 아니고, 설명을 위해 recursive로 지정되지 않은 나머지 key들에 대해서 처리 여부를 구분한 이름입니다.

말씀하신 바와 같이 includes 옵션에 해당하는 string[]에서는 나머지 키들을 recursive하게 변환하지 않기 때문에 false 옵션과 동일하게 excludes를 상속해도 실제로 영향을 주지 않기 때문에 일관성에는 문제가 없다고 생각합니다.

말씀드린 전제가 프로젝트 specific한 전제인지 판단을 먼저 해야겠네요.

2018-03-09 11:56 UTC, kyungmi commented on src/__tests__/camelize.ts
> +  })
이렇게 논리로만 얘기하면 교차점을 찾기 힘들 것 같으니 예를 한번 들어볼게요.

```
options = { excludes: ['a_b'], recursive: { excludes: ['C_D'] } }
```
라고 썼다면, 이 사용자가 원하는 건 무엇이었고, 실제 결과는 어떨까요?
실제로 이 사용자는 `a_b` 라는 키에 대해서는 recursive를 중단하고, `C_D`라는 키에 대해서는 그냥 단순히 키 변환만 막길 원했을 수 있습니다.
하지만 결과적으로 'a_b`, `C_D` 모두에 대해서 recursive가 중단됩니다.

그리고 위의 대답에서 "key는 변환하고 그 값인 오브젝트는 recursive하게 변환하고 싶지 않은 경우" 에 대해 말씀하신적이 있습니다. 이런 경우에는 `{ recursive: { excludes: ['key'] }}` 라고 쓰면 될 것 같은데, 반대로 "key는 변환하지 않고 그 값인 오브젝트는 recursive하게 변환하고 싶은 경우"에 대해서는 `{recursive: true, excludes: ['key']}`라고 쓸 수가 없습니다. 왜냐하면 일단 `excludes` 옵션을 쓰는 순간 `recursive`의 동작이 제한되기 때문입니다.

이게 바람직한 결과일까요? 저는 잘 모르겠습니다.
스토어에서 사용하지 않을거라고 해서 이런 의도로 사용할 사용자가 없을 거라고는 말할 수 없습니다. 만약 사용자가 이런 결과를 원한다면 이 API를 어떻게 쓰라고 설명해줄 수 있을까요?

각 옵션의 의미는 한 마디로 정의되는게 가장 좋고, 거기에 예외가 달리는 순간 사용자가 직관적으로 활용하는 것을 막고 한번 더 생각하게 만듭니다.(`recursive` 설명으로 추가된 `If set true or { excludes: string[] } with "excludes" option, recursive inherit excludes option.`와 같은 예외를 말합니다.) API는 간결하면 간결할 수록 좋다고 생각합니다. 말씀하신 것과 같은 sugar들을 굳이 추가해야 한다면 간결함 위에 첨가하는게 좋다고 생각합니다.

그리고 실제 아래 1),2)번의 결과는 같고 3)은 다릅니다.
```
1) { recursive: true, excludes: ['a', 'b', 'c'] } // a,b,c 에 대해 recursive하게 동작하지 않고, a,b,c 키에 대한 변환도 하지 않는다.
2) { recursive: { excludes: ['a', 'b', 'c'] }, excludes: ['a', 'b', 'c'] } // a,b,c에 대해 recursive하게 동작하지 않고 a,b,c 키에 대한 변환도 하지 않는다.
3) { recursive: { excludes: ['a', 'b', 'c'] } } // a,b,c에 대해 recursive하게 동작하지 않고, a,b,c 키에 대한 변환은 한다.
```
실제로 README 파일을 자세히 읽지 않으면, 1),2) 두가지 경우가 같은 결과를 주었을 때, 어차피 같은 동작(키 변환도 막고, 동시에 recursive 동작도 막음)을 하는 `excludes`와 `recursive.excludes`가 함께 있는지에 대해서 생각하게 될 것입니다(제가 처음에 그랬던 것처럼). 결국 두 옵션이 같다고 받아들이게 되면 3)의 동작이 헷갈리기 시작합니다. 만약 2),3)을 먼저 봤을 때는 명확하게 `recursive.excludes`와 `recursive`의 역할이 구분되어 있다고 생각할 것이기 때문에 1)이 헷갈리겠죠. 
문서를 읽으면 해결될 문제이지만, 보통 그렇게 상세하게 문서를 읽는 경우는 문제에 부딪혔을 때입니다.

스토어에 얼마나 복잡한 예가 있는진 모르겠지만, Restful API에 따라 모델은 정해져 있을테니, 중복으로 키를 적어야 하는 문제는 모델에 맞는 변환 옵션들을 따로 관리한다면 간단하게 해결될 문제라고 생각합니다.

2018-03-10 12:48 UTC, namenu commented on src/__tests__/camelize.ts
> +  })
**1. 전제가 적절한가**

`camelCase로 변환하지 않는 키는 js에서 사용하지 않는다`라는 전제는 스토어팀을 벗어나면 통용되기가 어렵다고 생각합니다.
PR이 통과되려면 스토어팀 외부에서 동의할 수 있는 수준으로 전제조건을 느슨하게 하거나, 스토어팀만의 separate way를 가는 것이 좋겠습니다.



**2. 인터페이스의 설계가 적절한가**

위의 전제만 통과된다면 저는 구현에 대한 리뷰는 다른 분들의 의견을 수렴하여 의사결정을 할게요.

물론 asana에서 댓글로 남겼듯이, 저는 조금 단순해지면 좋겠다는 입장입니다.
제 단순([單](http://hanja.naver.com/hanja?q=%E5%96%AE)[純](http://hanja.naver.com/hanja?q=%E7%B4%94))의 의미는 한 번에 한가지만 수행하는 것입니다. (옵션이든 함수든)

API가 '쉬운지/어려운지'는 사람마다 다를 수 있어서 논의에 포함시키면 끝이 없습니다.

2018-03-11 13:28 UTC, earus commented on src/__tests__/camelize.ts
> +  })
OCC가 제공하는 기능이

1) 특정 키 이름을 변환 대상에 포함시키거나 제외시킬 수 있다.
2) 특정 키 값을 재귀적으로 변환 대상에 포함시키거나 제외시킬 수 있다.

일 때 단순한 방식을 찾는다면

1) 모든 키 이름은 기본적으로 변환한다.
2) 단, 1번에 예외대상을 추가할 수 있다.
3) 모든 키의 값들은 재귀적으로 변환한다.
4) 단, 3번에 예외대상을 추가할 수 있다.

같은 방식도 그 중 하나로 생각해 볼 수 있는데요. 이 경우 넘길 수 있는 옵션은 `key_name_convert_excludes`, `recursive_excludes` 정도가 될거고, 현재 제공하는 인터페이스에 비해 알아야 하는 지식이 훨씬 적습니다. 이런 방식이 정답이라는 것이 아니라 더 단순한 인터페이스를 고민해볼 여지가 있다는 것을 말하고 싶은거고요.

OCC는 타팀이 함께 사용하는 라이브러리이므로 스토어팀의 상황이 기준이 되어서는 안되며, 오랜 논의를 통해서도 타팀으로부터 동의를 구할 수 없다면 이 MR을 재고해봐야 할 것 같습니다. 합의된 인터페이스를 찾고 스토어팀 입장에서 비효율적인 부분은 OCC를 이용하는 팀 내 별도 유틸리티를 만드는 것도 고려해 볼 수 있을 것 같은데, 시간적으로 여유가 되지 않는다면 팀 내 라이브러리로 두는게 좋겠다는게 제 생각입니다.

2018-03-13 00:20 UTC, kyungmi commented on src/__tests__/camelize.ts
> +  })
@J132134 말씀하신 전제만으로는 설득력이 부족한 것 같습니다. 이 부분만 수정해주시면 머지할게요.

2018-03-13 05:31 UTC, kyungmi approved these changes

2018-03-13 05:34 UTC, kyungmi commented
`excludes`옵션과 함께 존재했을때 직접적인 모순이 발생할 수 있는 recursive includes(`recursive: string[]`)옵션만 삭제하고 나머지는 @J132134 님이 제안하신 방식을 그대로 따르기로 했습니다.

2018-03-13 05:34 UTC, merged